"""Audio capture, playback and buffers."""

from app.audio.audioBuffer import AudioBuffer
from app.audio.input import (
    AudioInput,
    AudioInputError,
    MemoryAudioInput,
    SoundDeviceInput,
    WavFileInput,
    createAudioInput,
    listInputDevices,
    resampleBuffer,
    splitIntoFrames,
)
from app.audio.output import (
    AudioOutput,
    AudioOutputError,
    MemoryAudioOutput,
    SoundDeviceOutput,
    WavFileOutput,
    createAudioOutput,
    listOutputDevices,
)
from app.audio.vad import (
    EnergyVadProvider,
    SegmenterSettings,
    SegmentState,
    SileroVadProvider,
    SpeechSegmenter,
    VadError,
    VadProvider,
    createVadProvider,
)
from app.audio.wakeWord import (
    AlwaysAwakeProvider,
    Detection,
    ManualWakeWordProvider,
    OpenWakeWordProvider,
    WakeWordError,
    WakeWordProvider,
    createWakeWordProvider,
)

__all__ = [
    "AlwaysAwakeProvider",
    "AudioBuffer",
    "AudioInput",
    "AudioInputError",
    "AudioOutput",
    "AudioOutputError",
    "Detection",
    "EnergyVadProvider",
    "ManualWakeWordProvider",
    "MemoryAudioInput",
    "MemoryAudioOutput",
    "OpenWakeWordProvider",
    "SegmentState",
    "SegmenterSettings",
    "SileroVadProvider",
    "SoundDeviceInput",
    "SoundDeviceOutput",
    "SpeechSegmenter",
    "VadError",
    "VadProvider",
    "WakeWordError",
    "WakeWordProvider",
    "WavFileInput",
    "WavFileOutput",
    "createAudioInput",
    "createAudioOutput",
    "createVadProvider",
    "createWakeWordProvider",
    "listInputDevices",
    "listOutputDevices",
    "resampleBuffer",
    "splitIntoFrames",
]
