"""Coqui XTTS-v2 text-to-speech.

All XTTS- and torch-specific handling is confined to this module: checkpoint
loading quirks, conditioning latents, device placement and the model's input
length limit. Nothing here escapes through
:class:`~app.speech.textToSpeech.TextToSpeechProvider`.

Licence note: XTTS-v2 is published under the Coqui Public Model Licence, which
permits non-commercial use only. Downloading the model requires agreeing to it
by setting ``COQUI_TOS_AGREED=1``.
"""

from __future__ import annotations

import asyncio
import gc
import hashlib
import logging
import os
import re
import time
from collections.abc import AsyncIterator
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, ClassVar

from app.audio.audioBuffer import AudioBuffer
from app.speech.device import describeCudaDevice, resolveDevice
from app.speech.textToSpeech import (
    ProviderUnavailableError,
    SpeechSynthesisError,
    TextToSpeechProvider,
)
from app.speech.voices import VoiceLibrary, VoiceNotFoundError

if TYPE_CHECKING:
    from app.config import Settings

logger = logging.getLogger(__name__)

DEFAULT_MODEL = "tts_models/multilingual/multi-dataset/xtts_v2"

# XTTS degrades and eventually truncates on long inputs, so text is split into
# chunks below this length and the resulting audio joined.
MAX_CHARACTERS_PER_CHUNK = 220

# XTTS-v2 ships with studio speakers, so the assistant has a working voice
# before anyone records one. A voice of this name resolves to the speaker
# below unless the user has provided their own sample called "default".
DEFAULT_VOICE_ALIAS = "default"
DEFAULT_BUILT_IN_SPEAKER = "Claribel Dervla"

# Decoder steps per streamed piece. Smaller means audio sooner but more total
# work: measured on an RTX 3070, 10 gives the first piece in about 0.2 s while
# keeping generation comfortably ahead of playback. Below about 5, generation
# starts approaching real time and risks stuttering on a long reply.
DEFAULT_STREAM_CHUNK_SIZE = 10

# Pieces held between the model and the player. Bounded so that a fast GPU
# generating far ahead of playback does not hold a whole long reply in memory.
STREAM_QUEUE_DEPTH = 8

# The rate XTTS conditions on. Recordings are resampled to it, so anything
# above it in the source is discarded regardless.
REFERENCE_SAMPLE_RATE = 22050

# Shown at the moment someone decides whether to download the model, which is
# the one place the restriction is certain to be read. It says "and its
# outputs" because that is the part people miss: audio generated by XTTS
# carries the same non-commercial restriction as the model itself.
TOS_MESSAGE = (
    "XTTS-v2 is licensed under the Coqui Public Model Licence (CPML), which\n"
    "permits non-commercial use only --- of the model AND of the audio it\n"
    "generates. This project's own MIT licence grants no rights over it.\n"
    "\n"
    "Set COQUI_TOS_AGREED=1 to accept the CPML and allow the model to download:\n"
    '    $env:COQUI_TOS_AGREED = "1"\n'
    "\n"
    "For a synthesiser with no such restriction, set textToSpeech.provider to\n"
    "something else; nothing outside this file depends on XTTS. See NOTICE.md."
)


@dataclass(frozen=True, slots=True)
class SpeakerSource:
    """Where a voice's speaker characteristics come from.

    Either recordings the user supplied, or one of the model's built-in
    speakers. Both end up as the same pair of conditioning tensors.
    """

    name: str
    samples: tuple[Path, ...] = ()
    builtIn: bool = False

    @property
    def sampleCount(self) -> int:
        return len(self.samples)


class XttsProvider(TextToSpeechProvider):
    """XTTS-v2, loaded once and kept resident."""

    name: ClassVar[str] = "xtts"

    def __init__(
        self,
        *,
        voices: VoiceLibrary,
        modelName: str = DEFAULT_MODEL,
        voice: str = "default",
        language: str = "en",
        device: str = "auto",
        modelsDirectory: Path | None = None,
        useEmbeddingCache: bool = True,
        streamChunkSize: int = DEFAULT_STREAM_CHUNK_SIZE,
    ) -> None:
        self._voices = voices
        self._modelName = modelName
        self._voice = voice
        self._language = language
        self._devicePreference = device
        self._modelsDirectory = modelsDirectory
        self._useEmbeddingCache = useEmbeddingCache
        self._streamChunkSize = streamChunkSize

        self._api: Any = None
        self._model: Any = None
        self._torch: Any = None
        self._device: str | None = None
        self._sampleRate = 24000
        self._conditioningCache: dict[str, tuple[Any, Any]] = {}

    @classmethod
    def fromSettings(cls, settings: Settings, voices: VoiceLibrary) -> XttsProvider:
        return cls(
            voices=voices,
            modelName=settings.textToSpeech.model or DEFAULT_MODEL,
            voice=settings.textToSpeech.voice,
            language=settings.textToSpeech.language,
            device=settings.textToSpeech.device,
            modelsDirectory=settings.paths.models,
            useEmbeddingCache=settings.textToSpeech.useEmbeddingCache,
            streamChunkSize=settings.textToSpeech.streamChunkSize,
        )

    # --- Lifecycle -------------------------------------------------------

    @property
    def isLoaded(self) -> bool:
        return self._api is not None

    @property
    def sampleRate(self) -> int:
        return self._sampleRate

    async def load(self) -> None:
        if self.isLoaded:
            logger.debug("XTTS already loaded, not reloading")
            return

        started = time.perf_counter()
        await asyncio.to_thread(self._loadBlocking)
        logger.info(
            "XTTS loaded on %s in %.1fs", self._device, time.perf_counter() - started
        )

    def _loadBlocking(self) -> None:
        if self._modelsDirectory is not None:
            # Keep downloads inside the project rather than a user-wide cache.
            self._modelsDirectory.mkdir(parents=True, exist_ok=True)
            os.environ.setdefault("TTS_HOME", str(self._modelsDirectory.resolve()))

        torch = _importTorch()
        self._torch = torch
        self._device = resolveDevice(self._devicePreference)

        if self._device == "cuda":
            description = describeCudaDevice()
            if description:
                logger.info("Using CUDA device: %s", description)

        _registerCheckpointSafeGlobals(torch)
        api = _importTtsApi()

        try:
            self._api = api(model_name=self._modelName, progress_bar=True)
            self._api.to(self._device)
        except Exception as error:  # surface a usable message
            raise _describeLoadFailure(error, self._modelName) from error

        # The low-level model allows conditioning latents to be computed once
        # per voice instead of on every utterance.
        self._model = getattr(getattr(self._api, "synthesizer", None), "tts_model", None)
        if self._model is None:
            logger.warning(
                "Low-level XTTS model unavailable; falling back to the high-level API. "
                "Speaker conditioning will be recomputed per utterance."
            )
        else:
            configured = getattr(getattr(self._model, "config", None), "audio", None)
            self._sampleRate = int(
                getattr(configured, "output_sample_rate", None) or self._sampleRate
            )

    async def unload(self) -> None:
        if not self.isLoaded:
            return
        await asyncio.to_thread(self._unloadBlocking)
        logger.info("XTTS unloaded")

    def _unloadBlocking(self) -> None:
        self._conditioningCache.clear()
        self._model = None
        self._api = None
        gc.collect()
        if self._torch is not None and self._device == "cuda":
            try:
                self._torch.cuda.empty_cache()
            except Exception as error:  # teardown must not raise  # noqa: BLE001
                logger.debug("Ignoring CUDA cache clear failure: %s", error)

    # --- Synthesis -------------------------------------------------------

    async def synthesise(
        self,
        text: str,
        *,
        voice: str | None = None,
        language: str | None = None,
    ) -> AudioBuffer:
        if not self.isLoaded:
            raise SpeechSynthesisError("XTTS is not loaded; call load() first")

        cleaned = text.strip()
        if not cleaned:
            return AudioBuffer.silence(0.0, self._sampleRate)

        resolved = self.resolveSpeaker(voice or self._voice)

        return await asyncio.to_thread(
            self._synthesiseBlocking, cleaned, resolved, language or self._language
        )

    def resolveSpeaker(self, name: str) -> SpeakerSource:
        """Resolve a voice name to samples or a built-in speaker.

        User recordings win over built-in speakers of the same name, so adding
        a sample is all it takes to override a default.
        """
        try:
            voice = self._voices.get(name)
        except VoiceNotFoundError as error:
            builtIn = self._builtInSpeakerNames()

            if name in builtIn:
                return SpeakerSource(name=name, builtIn=True)

            if name == DEFAULT_VOICE_ALIAS and DEFAULT_BUILT_IN_SPEAKER in builtIn:
                logger.debug(
                    "Voice %r resolved to built-in speaker %r",
                    name,
                    DEFAULT_BUILT_IN_SPEAKER,
                )
                return SpeakerSource(name=DEFAULT_BUILT_IN_SPEAKER, builtIn=True)

            if not builtIn:
                raise
            raise VoiceNotFoundError(
                f"{error}\n\nBuilt-in speakers are also available: "
                f"{', '.join(builtIn[:8])}"
                f"{f', and {len(builtIn) - 8} more' if len(builtIn) > 8 else ''}"
            ) from error

        return SpeakerSource(name=voice.name, samples=voice.samples)

    def _builtInSpeakerNames(self) -> list[str]:
        """Studio speakers shipped with the model, if it exposes any."""
        manager = getattr(self._model, "speaker_manager", None)
        speakers = getattr(manager, "speakers", None)
        if not speakers:
            return []
        return sorted(speakers)

    @property
    def supportsStreaming(self) -> bool:
        return self._streamChunkSize > 0 and self._model is not None

    async def synthesiseStream(
        self,
        text: str,
        *,
        voice: str | None = None,
        language: str | None = None,
    ) -> AsyncIterator[AudioBuffer]:
        """Yield audio while the utterance is still being generated.

        XTTS decodes autoregressively, so the beginning of an utterance exists
        long before the end. Waiting for the whole thing costs 1.7 s on a long
        sentence where the first piece is ready in 0.2 s.

        The model's generator is synchronous and blocking, so it runs in a
        worker thread and hands pieces back through a bounded queue. Bounded
        because a fast GPU would otherwise generate a long reply far ahead of
        playback and hold all of it in memory.
        """
        if not self.isLoaded:
            raise SpeechSynthesisError("XTTS is not loaded; call load() first")

        cleaned = text.strip()
        if not cleaned:
            return

        if self._model is None:
            # No low-level model, so there is nothing to stream from.
            yield await self.synthesise(cleaned, voice=voice, language=language)
            return

        source = self.resolveSpeaker(voice or self._voice)
        resolvedLanguage = language or self._language

        for piece in splitText(cleaned, MAX_CHARACTERS_PER_CHUNK):
            async for audio in self._streamPiece(piece, source, resolvedLanguage):
                yield audio

    async def _streamPiece(
        self, text: str, voice: SpeakerSource, language: str
    ) -> AsyncIterator[AudioBuffer]:
        queue: asyncio.Queue[Any] = asyncio.Queue(maxsize=STREAM_QUEUE_DEPTH)
        loop = asyncio.get_running_loop()
        finished = object()

        def produce() -> None:
            try:
                gptCondLatent, speakerEmbedding = self._conditioningFor(voice)
                for waveform in self._model.inference_stream(
                    text,
                    language,
                    gptCondLatent,
                    speakerEmbedding,
                    stream_chunk_size=self._streamChunkSize,
                ):
                    audio = _waveformToBuffer(waveform, self._sampleRate)
                    asyncio.run_coroutine_threadsafe(queue.put(audio), loop).result()
            except Exception as error:  # noqa: BLE001 - reported to the consumer
                asyncio.run_coroutine_threadsafe(queue.put(error), loop).result()
            else:
                asyncio.run_coroutine_threadsafe(queue.put(finished), loop).result()

        worker = asyncio.create_task(asyncio.to_thread(produce))
        try:
            while True:
                item = await queue.get()
                if item is finished:
                    break
                if isinstance(item, BaseException):
                    raise SpeechSynthesisError(
                        f"XTTS failed while streaming {text[:40]!r}: {item}"
                    ) from item
                yield item
        finally:
            await worker

    def _synthesiseBlocking(
        self, text: str, voice: SpeakerSource, language: str
    ) -> AudioBuffer:
        chunks = splitText(text, MAX_CHARACTERS_PER_CHUNK)
        if len(chunks) > 1:
            logger.debug("Split %d characters into %d chunks", len(text), len(chunks))

        buffer = AudioBuffer(data=b"", sampleRate=self._sampleRate)
        for chunk in chunks:
            buffer = buffer.concatenate(self._synthesiseChunk(chunk, voice, language))
        return buffer

    def _synthesiseChunk(
        self, text: str, voice: SpeakerSource, language: str
    ) -> AudioBuffer:
        try:
            if self._model is not None:
                gptCondLatent, speakerEmbedding = self._conditioningFor(voice)
                result = self._model.inference(
                    text,
                    language,
                    gptCondLatent,
                    speakerEmbedding,
                )
                waveform = result["wav"]
            elif voice.builtIn:
                waveform = self._api.tts(text=text, speaker=voice.name, language=language)
            else:
                waveform = self._api.tts(
                    text=text,
                    speaker_wav=[str(path) for path in voice.samples],
                    language=language,
                )
        except Exception as error:  # model errors vary widely
            raise SpeechSynthesisError(
                f"XTTS failed to synthesise {text[:40]!r}: {error}"
            ) from error

        return _waveformToBuffer(waveform, self._sampleRate)

    def _conditioningFor(self, voice: SpeakerSource) -> tuple[Any, Any]:
        """Compute or reuse the speaker conditioning for ``voice``.

        These latents depend only on the speaker, so they are cached in memory
        for the process and, for cloned voices, on disk between runs.
        """
        if voice.name in self._conditioningCache:
            return self._conditioningCache[voice.name]

        if voice.builtIn:
            conditioning = self._builtInConditioning(voice.name)
            self._conditioningCache[voice.name] = conditioning
            return conditioning

        cachePath = self._cachePathFor(voice)
        if self._useEmbeddingCache and cachePath is not None and cachePath.is_file():
            loaded = self._loadCachedConditioning(cachePath)
            if loaded is not None:
                self._conditioningCache[voice.name] = loaded
                logger.info("Loaded cached speaker embedding for %r", voice.name)
                return loaded

        started = time.perf_counter()
        gptCondLatent, speakerEmbedding = self._computeConditioning(voice)
        logger.info(
            "Computed speaker embedding for %r from %d sample(s) in %.1fs",
            voice.name,
            voice.sampleCount,
            time.perf_counter() - started,
        )

        conditioning = (gptCondLatent, speakerEmbedding)
        self._conditioningCache[voice.name] = conditioning

        if self._useEmbeddingCache and cachePath is not None:
            self._saveCachedConditioning(cachePath, conditioning)

        return conditioning

    def _builtInConditioning(self, name: str) -> tuple[Any, Any]:
        """Read a studio speaker's precomputed latents from the model.

        These ship with the checkpoint, so there is nothing to compute or cache
        on disk.
        """
        entry = self._model.speaker_manager.speakers[name]
        try:
            return entry["gpt_cond_latent"], entry["speaker_embedding"]
        except (KeyError, TypeError) as error:
            raise SpeechSynthesisError(
                f"Built-in speaker {name!r} is not in the expected format: {error}"
            ) from error

    def _computeConditioning(self, voice: SpeakerSource) -> tuple[Any, Any]:
        """Turn a speaker's recordings into the two things XTTS conditions on.

        This mirrors ``get_conditioning_latents``, but reads the audio itself.
        The library's own loader goes through torchaudio, which since torch 2.9
        delegates to torchcodec and so needs FFmpeg installed system-wide ---
        a dependency this project otherwise does not have, and one that is not
        present on Windows by default. Everything else here follows the
        library: each recording is trimmed to the reference limit, contributes
        a speaker embedding, and the recordings are concatenated before the
        GPT latents are taken.
        """
        torch = self._torch
        settings = self._conditioningSettings()
        loadRate = REFERENCE_SAMPLE_RATE
        maximumSamples = loadRate * int(settings.get("max_ref_length", 30))

        embeddings = []
        audios = []

        with torch.inference_mode():
            for path in voice.samples:
                audio = self._loadReference(path, loadRate)[:, :maximumSamples]
                if settings.get("sound_norm_refs"):
                    audio = (audio / torch.abs(audio).max()) * 0.75
                embeddings.append(self._model.get_speaker_embedding(audio, loadRate))
                audios.append(audio)

            if not audios:
                raise SpeechSynthesisError(
                    f"Voice {voice.name!r} has no readable recordings."
                )

            latent = self._model.get_gpt_cond_latents(
                torch.cat(audios, dim=-1),
                loadRate,
                length=settings.get("gpt_cond_len", 30),
                chunk_length=settings.get("gpt_cond_chunk_len", 4),
            )
            embedding = torch.stack(embeddings).mean(dim=0)

        return latent, embedding

    def _loadReference(self, path: Path, sampleRate: int) -> Any:
        """Read one recording as mono audio at the rate XTTS conditions on."""
        try:
            import librosa
        except ImportError as error:
            raise ProviderUnavailableError(
                "Reading voice recordings requires librosa.\n"
                'Install with: pip install -e ".[tts]"'
            ) from error

        try:
            samples, _ = librosa.load(str(path), sr=sampleRate, mono=True)
        except Exception as error:
            raise SpeechSynthesisError(
                f"Could not read the voice recording {path.name}: {error}"
            ) from error

        audio = self._torch.tensor(samples, dtype=self._torch.float32).unsqueeze(0)
        return audio.clip(-1, 1).to(self._device)

    def _conditioningSettings(self) -> dict[str, Any]:
        """How much of a recording to use, taken from the model's own config.

        ``get_conditioning_latents`` defaults to six seconds for the GPT
        conditioning that carries prosody, while the shipped config asks for
        thirty. Coqui's own synthesis path passes the config through; calling
        the method bare quietly ignores everything a speaker recorded after the
        first six seconds, except for timbre.
        """
        config = getattr(self._model, "config", None)
        if config is None:
            return {}

        settings: dict[str, Any] = {}
        for argument, attribute in (
            ("gpt_cond_len", "gpt_cond_len"),
            ("gpt_cond_chunk_len", "gpt_cond_chunk_len"),
            ("max_ref_length", "max_ref_len"),
            ("sound_norm_refs", "sound_norm_refs"),
        ):
            value = getattr(config, attribute, None)
            if value is not None:
                settings[argument] = value
        return settings

    def _cachePathFor(self, voice: SpeakerSource) -> Path | None:
        """Cache path keyed on the samples, so edits invalidate it."""
        try:
            fingerprint = hashlib.sha256()
            fingerprint.update(self._modelName.encode("utf-8"))
            # How much of the recording was used is part of what the embedding
            # is, so changing it has to invalidate anything cached before.
            fingerprint.update(repr(sorted(self._conditioningSettings().items())).encode())
            for path in voice.samples:
                stat = path.stat()
                fingerprint.update(path.name.encode("utf-8"))
                fingerprint.update(str(stat.st_size).encode("utf-8"))
                fingerprint.update(str(int(stat.st_mtime)).encode("utf-8"))
        except OSError as error:
            logger.debug("Could not fingerprint voice samples: %s", error)
            return None

        directory = self._voices.cacheDirectory
        return directory / f"{voice.name}-{fingerprint.hexdigest()[:16]}.pth"

    def _loadCachedConditioning(self, path: Path) -> tuple[Any, Any] | None:
        try:
            payload = self._torch.load(path, map_location=self._device, weights_only=True)
            return payload["gptCondLatent"], payload["speakerEmbedding"]
        except Exception as error:  # a bad cache must not be fatal  # noqa: BLE001
            logger.warning("Ignoring unreadable embedding cache %s: %s", path, error)
            return None

    def _saveCachedConditioning(self, path: Path, conditioning: tuple[Any, Any]) -> None:
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            self._torch.save(
                {
                    "gptCondLatent": conditioning[0],
                    "speakerEmbedding": conditioning[1],
                },
                path,
            )
            logger.debug("Cached speaker embedding at %s", path)
        except Exception as error:  # caching is best effort  # noqa: BLE001
            logger.warning("Could not write embedding cache %s: %s", path, error)

    # --- Introspection ---------------------------------------------------

    def availableVoices(self) -> list[str]:
        """Cloned voices first, then the model's built-in speakers."""
        local = self._voices.listVoices()
        builtIn = [name for name in self._builtInSpeakerNames() if name not in local]
        return local + builtIn

    def describe(self) -> str:
        device = self._device or f"{self._devicePreference} (unresolved)"
        return f"xtts [{self._modelName}] on {device}"


# --- Module helpers ------------------------------------------------------


def splitText(text: str, maximumCharacters: int) -> list[str]:
    """Split text into chunks on sentence boundaries where possible."""
    if len(text) <= maximumCharacters:
        return [text]

    sentences = re.split(r"(?<=[.!?])\s+", text)
    chunks: list[str] = []
    current = ""

    for sentence in sentences:
        # A single sentence longer than the limit is broken on whitespace.
        while len(sentence) > maximumCharacters:
            cut = sentence.rfind(" ", 0, maximumCharacters)
            if cut <= 0:
                cut = maximumCharacters
            if current:
                chunks.append(current)
                current = ""
            chunks.append(sentence[:cut].strip())
            sentence = sentence[cut:].strip()

        if not current:
            current = sentence
        elif len(current) + 1 + len(sentence) <= maximumCharacters:
            current = f"{current} {sentence}"
        else:
            chunks.append(current)
            current = sentence

    if current:
        chunks.append(current)
    return [chunk for chunk in chunks if chunk]


def _waveformToBuffer(waveform: Any, sampleRate: int) -> AudioBuffer:
    """Convert a model waveform to an :class:`AudioBuffer`.

    ``inference`` returns a numpy array but ``inference_stream`` yields tensors
    still on the GPU, so anything tensor-shaped is brought back to the host
    first. Uses numpy for the conversion, since a Python loop over a few
    hundred thousand samples is needlessly slow.
    """
    if hasattr(waveform, "detach"):
        waveform = waveform.detach().cpu()

    try:
        import numpy
    except ImportError:
        return AudioBuffer.fromFloatSamples(list(waveform), sampleRate)

    array = numpy.asarray(waveform, dtype=numpy.float32).flatten()
    clipped = numpy.clip(array, -1.0, 1.0)
    encoded = (clipped * 32767.0).round().astype("<i2")
    return AudioBuffer(data=encoded.tobytes(), sampleRate=sampleRate)


def _importTorch() -> Any:
    try:
        import torch
    except ImportError as error:
        raise ProviderUnavailableError(
            "XTTS requires PyTorch.\n"
            'Install with: pip install -e ".[tts]"\n'
            "For GPU support install a CUDA build from https://pytorch.org first."
        ) from error
    return torch


def _importTtsApi() -> Any:
    try:
        from TTS.api import TTS
    except ImportError as error:
        raise ProviderUnavailableError(
            "XTTS requires the 'coqui-tts' package (the maintained fork of Coqui TTS; "
            "the original 'TTS' package has no release for Python 3.13).\n"
            'Install with: pip install -e ".[tts]"'
        ) from error
    return TTS


def _registerCheckpointSafeGlobals(torch: Any) -> None:
    """Allow XTTS checkpoints to load under torch 2.6+.

    torch 2.6 changed ``torch.load`` to default to ``weights_only=True``, which
    refuses the config objects pickled inside XTTS checkpoints. Allow-listing
    those specific classes keeps the safety default everywhere else.
    """
    register = getattr(torch.serialization, "add_safe_globals", None)
    if register is None:
        return

    allowed: list[type] = []
    for moduleName, names in (
        ("TTS.tts.configs.xtts_config", ("XttsConfig",)),
        ("TTS.tts.models.xtts", ("XttsAudioConfig", "XttsArgs")),
        ("TTS.config.shared_configs", ("BaseDatasetConfig",)),
    ):
        try:
            module = __import__(moduleName, fromlist=list(names))
        except ImportError:
            continue
        for name in names:
            candidate = getattr(module, name, None)
            if isinstance(candidate, type):
                allowed.append(candidate)

    if allowed:
        try:
            register(allowed)
            logger.debug("Allow-listed %d XTTS config classes for torch.load", len(allowed))
        except Exception as error:  # never block loading  # noqa: BLE001
            logger.debug("Could not register safe globals: %s", error)


def _describeLoadFailure(error: Exception, modelName: str) -> Exception:
    """Translate opaque load failures into actionable messages."""
    text = str(error).lower()

    if "tos" in text or "terms" in text or "license" in text or "licence" in text:
        return ProviderUnavailableError(f"{TOS_MESSAGE}\n\nOriginal error: {error}")

    if "weights_only" in text or "unsupported global" in text:
        return ProviderUnavailableError(
            "The XTTS checkpoint was rejected by torch's safe-loading policy. "
            "This usually means the installed coqui-tts and torch versions disagree; "
            'reinstalling with pip install -e ".[tts]" normally resolves it.\n\n'
            f"Original error: {error}"
        )

    if "out of memory" in text:
        return ProviderUnavailableError(
            "Not enough GPU memory to load XTTS. Set textToSpeech.device to 'cpu', "
            "or free VRAM by closing other GPU applications.\n\n"
            f"Original error: {error}"
        )

    return ProviderUnavailableError(f"Could not load XTTS model {modelName!r}: {error}")


__all__ = ["XttsProvider", "VoiceNotFoundError", "splitText"]  # noqa: RUF022
